spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:/home/agnieszka/Desktop/todo-app-with-base-entity/todo-db'

  jpa:
    hibernate:
      ddl-auto: validate